### ISSUE TITLE
Cycle involving elements

### ISSUE THREAD

**Issue by 89z** [otaviokr/topological-sort#8]
If I run this program:

~~~go
package main

import (
   "fmt"
   "github.com/otaviokr/topological-sort/toposort"
)

func main() {
   unsorted := map[string][]string{
      "main": []string{},
      "A": []string{"main"},
      "B": []string{"A"},
   }
   sorted, e := toposort.KahnSort(unsorted)
   if e != nil {
      panic(e)
   }
   fmt.Printf(sorted)
}
~~~

I get expected output. However if I remove `"main": []string{},`, I get:

~~~
panic: Cycle involving elements:
~~~

Shouldnt the module be able to determine the node from the other edges?

**Comment by otaviokr** [comment]
Hi @89z 
I understand your point 

The original idea was to have all nodes defined in the unsorted map - the map should be a list of all nodes in the graph and the details about they are connected to each other. It is easy to get the list of nodes, for example, because they are all the keys in the map.

But for a map with many leaves, this could result in a lot of empty slices defined, and enforcing to write the leaves with empty slices seems to be limiting, thinking about it now.

I will try something here to look for leaf nodes in the slice, even if they have not been defined in the map. This should be enough.

Also, the panic error is terrible. Iĺl try to fix that as well :smile:

**Comment by otaviokr** [comment]
Hi @89z 
I think this is OK now. If possible, run your tests and let me know if you find anything
Thanks for helping improve the code :1st_place_medal:

**Comment by 89z** [comment]
Yes looks good, thanks
